"""Look up display names for HotS talent IDs.

Replay tracker events store talents as their internal ``talentTreeId``
strings (``AbathurMasteryAdrenalineBoost``, ``RehgarPurification``, …).
For the BP popup we want a human-readable name in the current UI locale.

The lookup table comes from ``data/talent_names.json``, generated by
``scripts/fetch_talent_names.py`` from the HeroesToolChest gamestrings
mirror. Falls back to a heuristic ``CamelCase → spaced`` rewrite if the
ID is missing (post-patch talents that were added after our snapshot).
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

from .i18n import language

_DATA_PATH = Path(__file__).resolve().parent / "data" / "talent_names.json"

# Hero-name prefixes seen in talentTreeIds. Stripped during the heuristic
# fallback so an unknown ``MuradinExtraCharges`` still reads as
# "Extra Charges" rather than the raw camel-case mash.
_KNOWN_HERO_PREFIXES = (
    "Abathur", "Alarak", "Alexstrasza", "Ana", "Anduin", "Anubarak",
    "Artanis", "Arthas", "Auriel", "Azmodan", "Barbarian", "Blaze",
    "Brightwing", "Cassia", "Chen", "Chogall", "Chromie", "DVa", "Deathwing",
    "Deckard", "Dehaka", "Diablo", "Dryad", "ETC", "L90ETC", "Falstad",
    "Fenix", "Gall", "Garrosh", "Gazlowe", "Genji", "Greymane", "Guldan",
    "Hanzo", "Hogger", "Illidan", "Imperius", "Jaina", "Johanna", "Junkrat",
    "Kaelthas", "KelThuzad", "Kerrigan", "Kharazim", "LiLi", "LiMing",
    "Leoric", "Lostvikings", "Lucio", "Maiev", "Malfurion", "Malganis",
    "Malthael", "Medivh", "Mephisto", "Muradin", "Murky", "Nazeebo",
    "Nova", "Orphea", "Probius", "Qhira", "Ragnaros", "Raynor", "Rehgar",
    "Rexxar", "Samuro", "SgtHammer", "Sonya", "Stitches", "Stukov",
    "Sylvanas", "Tassadar", "TLV", "Thrall", "Tracer", "Tyrael", "Tyrande",
    "Uther", "Valeera", "Valla", "Varian", "Whitemane", "Xul", "Yrel",
    "Zagara", "Zarya", "Zeratul", "Zuljin",
)

# Bucket / category infixes — strip these out of the display name when
# falling back to the heuristic, since the player doesn't care that
# something is a "Mastery" tier internally.
_CATEGORY_RE = re.compile(
    r"(CombatStyle|Mastery|HeroicAbility|Heroic|Talent|TraitTalent|Trait)"
)
_CAMEL_SPLIT_RE = re.compile(r"(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")


@lru_cache(maxsize=1)
def _table() -> dict[str, dict[str, str]]:
    if not _DATA_PATH.is_file():
        return {}
    try:
        payload = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload.get("talents", {})


def _heuristic(talent_id: str) -> str:
    """Cheap fallback: strip the hero prefix + category infix, then split
    the leftover CamelCase. E.g. ``MuradinExtraCharges`` → ``Extra Charges``."""
    rest = talent_id
    for hero in _KNOWN_HERO_PREFIXES:
        if rest.startswith(hero) and len(rest) > len(hero):
            rest = rest[len(hero):]
            break
    rest = _CATEGORY_RE.sub("", rest)
    if not rest:
        return talent_id
    return _CAMEL_SPLIT_RE.sub(" ", rest).strip()


def talent_label(talent_id: str, *, lang: str | None = None) -> str:
    """Return a display name for ``talent_id`` in the requested or current
    UI language. Falls back to English if zh is missing, then to a
    heuristic readable form, then to the raw ID."""
    if not talent_id:
        return ""
    table = _table()
    entry = table.get(talent_id)
    code = (lang or language()).lower()
    if entry:
        # zh-first when the user is on zh; otherwise prefer en. Always
        # fall through to the other locale if the preferred one is
        # missing for this specific talent.
        if code.startswith("zh"):
            return entry.get("zh") or entry.get("en") or _heuristic(talent_id)
        return entry.get("en") or entry.get("zh") or _heuristic(talent_id)
    return _heuristic(talent_id)
