# PyInstaller spec for HotS Helper.
#
# Build on the target OS:
#   Windows:  pyinstaller packaging/hots-helper.spec --clean
#   macOS:    pyinstaller packaging/hots-helper.spec --clean
#
# onedir output (not onefile) so the bundled protocol*.py files can be
# loaded by importlib at runtime without extraction overhead.

import sys
from pathlib import Path

block_cipher = None

project_root = Path.cwd()
# Platform-specific icon for the launcher .exe / .app. ICO on Windows,
# ICNS on macOS, PNG fallback elsewhere. Generated by
# scripts/build_icons.py from src/hots_helper/ui/assets/icon.svg.
_icon_dir = project_root / "src" / "hots_helper" / "ui" / "assets"
if sys.platform == "win32":
    icon_file = str(_icon_dir / "icon.ico")
elif sys.platform == "darwin":
    _icns = _icon_dir / "icon.icns"
    icon_file = str(_icns) if _icns.is_file() else None
else:
    _png = _icon_dir / "icon-256.png"
    icon_file = str(_png) if _png.is_file() else None
# Use the standalone launcher (packaging/launcher.py) as the entry
# script. PyInstaller treats the entry as __main__, and __main__ has no
# parent package — so importing the UI directly via app.py would break
# every ``from ..config import …`` it does. The launcher is a plain
# top-level script that calls ``hots_helper.ui.app.main`` after the
# package is registered as an absolute import target.
entry = project_root / "packaging" / "launcher.py"


def _windows_vc_runtime_dlls() -> list[tuple[str, str]]:
    """Return ``(src, dest)`` pairs for the Visual C++ runtime DLLs.

    Python 3.13's ``python313.dll`` depends on ``vcruntime140.dll`` /
    ``vcruntime140_1.dll`` / ``msvcp140.dll`` / ``ucrtbase.dll`` (parts of
    the VC++ 2015-2022 Redistributable). On a developer's box those are
    almost always present (installed by VS, Office, games, drivers…) so
    PyInstaller's build doesn't notice they're missing. On a clean
    Windows machine the redistributable might not be installed, and the
    user gets:

        Failed to load Python DLL '...\\python313.dll'.
        LoadLibrary: 找不到指定的模块.

    To make the bundle self-contained we copy these DLLs into the
    ``_internal`` folder ourselves. The bundle ends up ~3-5 MB larger,
    but recipients don't have to install anything.
    """
    if sys.platform != "win32":
        return []
    import ctypes.util
    import os
    candidates = [
        "vcruntime140.dll",
        "vcruntime140_1.dll",  # 64-bit only — MSVC 2017+
        "msvcp140.dll",
        "msvcp140_1.dll",
        "msvcp140_2.dll",
        "concrt140.dll",
        "ucrtbase.dll",
    ]
    search_paths = [
        Path(os.environ.get("SystemRoot", "C:\\Windows")) / "System32",
        Path(sys.base_prefix),
        Path(sys.base_prefix) / "DLLs",
    ]
    out: list[tuple[str, str]] = []
    seen: set[str] = set()
    for name in candidates:
        if name in seen:
            continue
        for d in search_paths:
            p = d / name
            if p.is_file():
                out.append((str(p), "."))
                seen.add(name)
                break
    return out


binaries = _windows_vc_runtime_dlls()

datas = [
    # Bundle the vendored replay protocol files; runtime scans this dir.
    (str(project_root / "src" / "hots_helper" / "vendor"), "hots_helper/vendor"),
    # The SQL schema the DB loads at startup.
    (str(project_root / "src" / "hots_helper" / "db" / "schema.sql"), "hots_helper/db"),
    # Reference data (talent names, etc.) read at runtime via Path lookups.
    (str(project_root / "src" / "hots_helper" / "data"), "hots_helper/data"),
    # UI asset bundle: icon.svg + multi-res PNG/ICO/ICNS used at runtime
    # by hots_helper.ui.assets.app_icon().
    (str(project_root / "src" / "hots_helper" / "ui" / "assets"), "hots_helper/ui/assets"),
]

# RapidOCR ships its ONNX models + config alongside the package. Without
# this, the frozen app would need users to download models separately.
try:
    from PyInstaller.utils.hooks import collect_data_files
    datas += collect_data_files("rapidocr_onnxruntime")
except Exception:
    pass

# NOTE: we used to bundle heroprotocol/versions/ here. The parser now
# uses our own ``hots_helper.vendor.protocol*`` files exclusively (the
# upstream package can't even import in our frozen build because its
# __init__ chain reaches for the removed ``imp`` module on Python 3.12+).
# Skipping it saves ~8 MB.

hiddenimports = [
    # Make sure the whole hots_helper package and submodules ship — PyInstaller
    # is conservative about following dynamic imports.
    "hots_helper",
    "hots_helper.config",
    "hots_helper.i18n",
    "hots_helper.lookup",
    "hots_helper.bp",
    "hots_helper.stats",
    "hots_helper.vision",
    "hots_helper.db",
    "hots_helper.db.store",
    "hots_helper.parser",
    "hots_helper.parser.replay",
    "hots_helper.parser.protocols",
    "hots_helper.watcher",
    "hots_helper.watcher.ingest",
    "hots_helper.watcher.watcher",
    "hots_helper.cli",
    "hots_helper.cli.main",
    "hots_helper.ui",
    "hots_helper.ui.app",
    "hots_helper.ui.main_window",
    "hots_helper.ui.popup",
    "hots_helper.ui.aram",
    "hots_helper.ui.region_select",
    "hots_helper.ui.workers",
    "hots_helper.ui.hotkey",
    "hots_helper.ui.screenshot",
    "hots_helper.ui.calibrate",
    "hots_helper.ocr",
    "hots_helper.ocr.rapid",
    "hots_helper.vendor",
    "hots_helper.vendor.decoders",
    "hots_helper.data",
    "hots_helper.talent_names",
    # PySide6 modules referenced only lazily
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    # watchdog picks a platform-specific observer at runtime
    "watchdog.observers.fsevents",
    "watchdog.observers.read_directory_changes",
    "watchdog.observers.inotify",
    "watchdog.observers.kqueue",
    "watchdog.observers.polling",
    # RapidOCR + ONNX runtime (loaded lazily by hots_helper.ocr.rapid)
    "rapidocr_onnxruntime",
    "hots_helper.ocr.rapid",
    "onnxruntime",
    "onnxruntime.capi._pybind_state",
    "shapely",
    "shapely.geometry",
    "pyclipper",
]

# Platform-specific OCR backends are imported lazily by hots_helper.ocr.
if sys.platform == "win32":
    hiddenimports += [
        "hots_helper.ocr.winrt_ocr",
        "winrt.windows.media.ocr",
        "winrt.windows.graphics.imaging",
        "winrt.windows.storage",
        "winrt.windows.storage.streams",
        "winrt.windows.globalization",
        "winrt.windows.foundation",
        "winrt.windows.foundation.collections",
    ]
elif sys.platform == "darwin":
    hiddenimports += ["hots_helper.ocr.vision_macos"]

# --- Qt binary / data filter ----------------------------------------------
# Even after excluding the Python sub-modules, PyInstaller's PySide6 hook
# still drags every Qt6 DLL/dylib into ``a.binaries`` and every Qt
# translation/QML/plugin into ``a.datas``. Filter them out here. Anything
# under PySide6/Qt/{plugins,translations,qml,…} that matches a substring
# in ``_QT_DROP_TOKENS`` is removed from the final bundle.
#
# Tokens are matched case-insensitively against the destination path. Be
# careful not to match shared deps: e.g. don't add ``Network`` (matches
# Qt6Network.dll only on Win, but on Linux some other lib might collide).
_QT_DROP_TOKENS = (
    # Qt sub-frameworks we don't use
    "Qt6Network", "Qt63D", "Qt6Bluetooth", "Qt6Charts", "Qt6Concurrent",
    "Qt6DataVisualization", "Qt6DBus", "Qt6Designer", "Qt6Graphs",
    "Qt6Help", "Qt6Http", "Qt6Location", "Qt6Multimedia", "Qt6Nfc",
    "Qt6OpenGL", "Qt6Pdf", "Qt6Positioning", "Qt6PrintSupport",
    "Qt6Qml", "Qt6Quick", "Qt6RemoteObjects", "Qt6Scxml", "Qt6Sensors",
    "Qt6Serial", "Qt6SpatialAudio", "Qt6Sql", "Qt6StateMachine",
    "Qt6Svg", "Qt6Test", "Qt6TextToSpeech", "Qt6UiTools", "Qt6Web",
    "Qt6WebChannel", "Qt6WebEngine", "Qt6WebSockets", "Qt6Xml",
    "Qt5Compat",
    # Qt asset trees
    "PySide6/Qt/qml/", "PySide6/Qt/translations/",
    "PySide6/Qt/resources/", "PySide6/Qt/lib/QtWebEngineCore",
    "PySide6/Qt/plugins/multimedia",
    "PySide6/Qt/plugins/sqldrivers",
    "PySide6/Qt/plugins/position",
    "PySide6/Qt/plugins/sensors",
    "PySide6/Qt/plugins/scxml",
    "PySide6/Qt/plugins/printsupport",
    "PySide6/Qt/plugins/networkinformation",
    "PySide6/Qt/plugins/tls",
    "PySide6/Qt/plugins/canbus",
    "PySide6/Qt/plugins/geometryloaders",
    "PySide6/Qt/plugins/renderers",
    "PySide6/Qt/plugins/sceneparsers",
    "PySide6/Qt/plugins/webview",
    # opengl is bulky and we don't render 3D
    "Qt6OpenGL", "opengl32sw",
    # Devtools we never invoke
    "PySide6/qmlls", "PySide6/qmlformat", "PySide6/Designer",
    "PySide6/Linguist", "PySide6/Assistant", "PySide6/lupdate",
    "PySide6/lrelease", "PySide6/qmllint", "PySide6/qmlimportscanner",
    "PySide6/qmlcachegen", "PySide6/qmlpreview", "PySide6/qmlplugindump",
    "PySide6/qmlprofiler", "PySide6/qmlscene", "PySide6/qmltyperegistrar",
    "PySide6/Assistant.app", "PySide6/Designer.app", "PySide6/Linguist.app",
)


def _drop_qt_extras(entries):
    """Filter (name, src, kind) tuples in ``a.binaries`` / ``a.datas``."""
    out = []
    for entry in entries:
        dest = entry[0].replace("\\", "/")
        if any(tok.lower() in dest.lower() for tok in _QT_DROP_TOKENS):
            continue
        out.append(entry)
    return out


a = Analysis(
    [str(entry)],
    pathex=[str(project_root / "src")],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        "pytest",
        "PIL.ImageQt",
        # We don't import heroprotocol at runtime — vendored copies only.
        "heroprotocol",
        # PySide6: drop every Qt sub-module we don't import. The default
        # PySide6 hook tries to ship every Qt6 .dll plus every Python
        # binding (QtNetwork, QtMultimedia, QtSvg, Qt3D, Charts, Web*, …),
        # which is roughly 80–120 MB we don't need. We use only QtCore,
        # QtGui, QtWidgets — everything else goes.
        "PySide6.Qt3DAnimation",
        "PySide6.Qt3DCore",
        "PySide6.Qt3DExtras",
        "PySide6.Qt3DInput",
        "PySide6.Qt3DLogic",
        "PySide6.Qt3DRender",
        "PySide6.QtBluetooth",
        "PySide6.QtCharts",
        "PySide6.QtConcurrent",
        "PySide6.QtDataVisualization",
        "PySide6.QtDBus",
        "PySide6.QtDesigner",
        "PySide6.QtGraphs",
        "PySide6.QtGraphsWidgets",
        "PySide6.QtHelp",
        "PySide6.QtHttpServer",
        "PySide6.QtLocation",
        "PySide6.QtMultimedia",
        "PySide6.QtMultimediaWidgets",
        "PySide6.QtNetwork",
        "PySide6.QtNetworkAuth",
        "PySide6.QtNfc",
        "PySide6.QtOpenGL",
        "PySide6.QtOpenGLWidgets",
        "PySide6.QtPdf",
        "PySide6.QtPdfWidgets",
        "PySide6.QtPositioning",
        "PySide6.QtPrintSupport",
        "PySide6.QtQml",
        "PySide6.QtQuick",
        "PySide6.QtQuick3D",
        "PySide6.QtQuickControls2",
        "PySide6.QtQuickWidgets",
        "PySide6.QtRemoteObjects",
        "PySide6.QtScxml",
        "PySide6.QtSensors",
        "PySide6.QtSerialBus",
        "PySide6.QtSerialPort",
        "PySide6.QtSpatialAudio",
        "PySide6.QtSql",
        "PySide6.QtStateMachine",
        "PySide6.QtSvg",
        "PySide6.QtSvgWidgets",
        "PySide6.QtTest",
        "PySide6.QtTextToSpeech",
        "PySide6.QtUiTools",
        "PySide6.QtWebChannel",
        "PySide6.QtWebEngineCore",
        "PySide6.QtWebEngineQuick",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebSockets",
        "PySide6.QtXml",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# Strip the unused Qt assets pulled in by PySide6's default hook.
a.binaries = _drop_qt_extras(a.binaries)
a.datas = _drop_qt_extras(a.datas)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="HotS-Helper",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,  # no terminal window on Windows
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon_file,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="HotS-Helper",
)
